blogs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^archive/(?P<blog_id>[0-9]+)/$', views.archive, name="archive"),
    url(r'^archive/(?P<blog_id>[0-9]+)/edit/$', views.blog_update, name="blog_update"),
    url(r'^post/$', views.post, name="post"),
    url(r'^search/$', views.search, name="search"),
    url(r'^comment/(?P<comment_id>[0-9]+)/$', views.getComment, name="getComment"),
    url(r'^addComment/(?P<blog_id>[0-9]+)/$', views.addComment, name="addComment"),
    url(r'^addNestedComment/(?P<comment_id>[0-9]+)/$', views.addNestedComment, name="addNestedComment"),
    url(r'^updateComment/(?P<comment_id>[0-9]+)/$', views.updateComment, name="updateComment"),
    url(r'^category/(?P<category>.+)/$', views.categoryBlogs, name="category"),

    url(r'^ajax/saveDraft/$', views.saveDraft, name="saveDraft"),
    url(r'^ajax/removeDraft/$', views.removeDraft, name="removeDraft"),
]

games/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^minesweeper/$', views.minesweeper, name="minesweeper"),

    url(r'^ajax/minesweeper/post_score/$', views.mine_score_post, name="mine_score_post"),
    url(r'^ajax/minesweeper/get_score/$', views.mine_score_get, name="mine_score_get"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.i18n import JavaScriptCatalog
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^blogs/', include('blogs.urls', namespace="blogs")),
    url(r'^contact/', views.contact, name="contact"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^upload/', include('fileupload.urls', namespace="upload")),
    url(r'^games/', include('games.urls', namespace="games")),
    url(r'^api/blogs/', include("blogs.api.urls", namespace="blogs-api")),
]

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class MineScore(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    play_time = models.DateTimeField(auto_now_add=True, auto_now=False)
    time_spent = models.IntegerField(null=False)

    max_score_count = 15

    def __str__(self):
        return str(self.user) + " " + str(self.time_spent)

    class Meta:
        ordering = ('time_spent', 'play_time', 'user')

games/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.contrib.auth.models import User
from django.utils import timezone

from datetime import datetime

from .models import MineScore
# Create your views here.


def minesweeper(request):
    score_list = list(range(MineScore.max_score_count))
    return render(request, "minesweeper/mine.html", {"score_list": score_list})


@login_required
def mine_score_post(request):
    if request.is_ajax():
        result = -1
        if request.method == 'POST':
            post_data = request.POST
            time_spent = int(post_data.get("time_spent"))
            user_id = int(post_data.get("user_id"))

            user = User.objects.get(id=user_id)
            new_score = MineScore()
            new_score.user = user
            new_score.time_spent = time_spent

            scores = MineScore.objects.all()
            last_score = scores.last()
            if len(scores) < MineScore.max_score_count:
                new_score.save()
            elif time_spent < last_score.time_spent:
                last_score.delete()
                new_score.save()

            scores = MineScore.objects.all()
            for ind, score in enumerate(scores):
                if score.id == new_score.id:
                    result = ind + 1
                    break

        return JsonResponse({"result": result})
    else:
        raise Http404("Page not found!")


def mine_score_get(request):
    if request.is_ajax():
        scores = MineScore.objects.all().order_by("time_spent")
        res = []
        for score in scores:
            play_time = timezone.localtime(score.play_time)
            play_time_str = datetime.strftime(play_time, "%Y-%m-%d %H:%M:%S")
            res.append({"name": score.user.username, "time_spent": score.time_spent, "time_created": play_time_str})
        return JsonResponse({"result": res})
    else:
        raise Http404("Page not found!")

games/templates/minesweeper/mine.html
{% extends "mysite/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}
    {% trans "Minesweeper" %}
{% endblock %}

{% block additional_head %}
	<link href="{% static 'minesweeper/mine.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}
<div id="content-div">
	<div id="setDiv">
		{% trans "Height" %}
		<input type="number" value="16" min="4" max="64" on id="height">
		{% trans "Width" %}
		<input type="number" value="30" min="4" max="120" id="width">
		{% trans "Mine Count" %}
		<input type="number" value="99" min="1" max="471" id="count")>
		<input class="btn btn-primary" type="button" value="{% trans 'New Game' %}" id="confirm" onclick="start()">
		<input class="btn btn-success" type="button" value="{% trans 'High Score' %}" id="high_score" onclick="get_high_score()">
	</div>
	<div id="mineDiv"></div>
</div>

<div id="high-score-modal" class="modal">
	<div class="modal-content">
		<div class="modal-header">
			<span class="close">&times;</span>
			<div class="modal-title">
				{% trans "High Score" %}
			</div>
		</div>
		<div class="modal-body">
			<div class="modal-tip">
				<p>{% trans "scores of default difficulty with no cheating are recorded" %}</p>
			</div>

			<table id="high-score-table">
				<tr>
					<th>{% trans "Rank" %}</th>
					<th>{% trans "Name" context "Game" %}</th>
					<th>{% trans "Time Spent" %}</th>
					<th>{% trans "Record Datetime" %}</th>
				</tr>
				{% for score in score_list %}
				<tr>
					<td>{{ forloop.counter }}</td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
				{% endfor %}
			</table>
		</div>
		<div class="modal-footer">
			<button type="button" id="high-score-close" class="btn btn-primary">{% trans "OK" %}</button>
		</div>
	</div>
</div>

<div id="post_score_div" {% if user.is_authenticated %}data-user="{{ user.id }}"{% endif %} data-url="{% url 'games:mine_score_post' %}" data-csrf_token="{{ csrf_token }}"></div>
<div id="get_score_div" data-url="{% url 'games:mine_score_get' %}"></div>

<script src="{% static 'minesweeper/mine.js' %}">
</script>

{% endblock %}
