blogs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^archive/(?P<blog_id>[0-9]+)/$', views.archive, name="archive"),
    url(r'^archive/(?P<blog_id>[0-9]+)/edit/$', views.blog_update, name="blog_update"),
    url(r'^post/$', views.post, name="post"),
    url(r'^search/$', views.search, name="search"),
    url(r'^comment/(?P<comment_id>[0-9]+)/$', views.getComment, name="getComment"),
    url(r'^addComment/(?P<blog_id>[0-9]+)/$', views.addComment, name="addComment"),
    url(r'^addNestedComment/(?P<comment_id>[0-9]+)/$', views.addNestedComment, name="addNestedComment"),
    url(r'^updateComment/(?P<comment_id>[0-9]+)/$', views.updateComment, name="updateComment"),
    url(r'^category/(?P<category>.+)/$', views.categoryBlogs, name="category"),

    url(r'^ajax/saveDraft/$', views.saveDraft, name="saveDraft"),
    url(r'^ajax/removeDraft/$', views.removeDraft, name="removeDraft"),
]

fileupload/urls.py
# encoding: utf-8
from django.conf.urls import url
from fileupload.views import PictureCreateView, PictureDeleteView, PictureListView

urlpatterns = [
    url(r'^$', PictureCreateView.as_view(), name='upload-new'),
    url(r'^delete/(?P<pk>\d+)/$', PictureDeleteView.as_view(), name='upload-delete'),
    url(r'^view/$', PictureListView.as_view(), name='upload-view'),
]

games/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^minesweeper/$', views.minesweeper, name="minesweeper"),

    url(r'^ajax/minesweeper/post_score/$', views.mine_score_post, name="mine_score_post"),
    url(r'^ajax/minesweeper/get_score/$', views.mine_score_get, name="mine_score_get"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.i18n import JavaScriptCatalog
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^blogs/', include('blogs.urls', namespace="blogs")),
    url(r'^contact/', views.contact, name="contact"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^upload/', include('fileupload.urls', namespace="upload")),
    url(r'^games/', include('games.urls', namespace="games")),
    url(r'^api/blogs/', include("blogs.api.urls", namespace="blogs-api")),
]

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models

mysite/views.py
from django.shortcuts import render


def home(request):
    return render(request, "mysite/home.html", {})


def contact(request):
    return render(request, "mysite/contact.html", {})

mysite/templates/mysite/base.html
{% load static %}
{% load i18n %}
{% load avatar_tags %}
{% load mysite_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="Satori's personal website">
        <meta name="author" content="Komeiji Satori">

        <title>{% block title %}{% endblock %}</title>
        <!-- Add favicon -->
        <link rel="shortcut icon" href="{% static 'mysite/images/favicon.ico' %}">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
        <!--Font-awesome CSS-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <!--code style CSS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/highlight.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/styles/monokai-sublime.min.css">
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.min.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="{% static 'mysite/cover.css' %}" rel="stylesheet">
        <link href="{% static 'mysite/background.css' %}" rel="stylesheet">
        {% block additional_head %}
        {% endblock %}
    </head>

    <body>
        {% load_background %}
        {% load_hidden_background %}
        <div class="simple-image-div"></div>
        <nav class="navbar navbar-default" id="navigation-bar">
            <div class="container">
                <div class="navbar-header">
                    <div class="navbar-header navbar-text">
                        {% if user.is_authenticated %}
                            <a href="{% url 'dashboard' %}" style="text-decoration: none;">{% avatar request.user 27 %} {{ request.user.username }}
                            <span class="badge" data-ajax-url="{% url 'unread_notification_count' %}" id="unread-notifications"></span>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div id="navbar">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'auth_logout' %}"><i class="fa fa-sign-out" aria-hidden="true"> {% trans "Log Out" %}</i></a></li>
                        {% else %}
                        <li><a href="{% url 'auth_login' %}"><i class="fa fa-sign-in" aria-hidden="true"> {% trans "Log In" %}</i></a></li>
                        <li><a href="{% url 'registration_register' %}"><i class="fa fa-user-plus" aria-hidden="true"> {% trans "Register" %}</i></a></li>
                        {% endif %}

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-globe"></i> {% trans "Language" %}<span class="caret"></span>
                            </a>
                            <div class="lang-div dropdown-menu" role="menu">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <a class="lang-item btn {% if language.code == LANGUAGE_CODE %}btn-primary{% else %}btn-default{% endif %}" onclick="$('#lang_type').val('{{ language.code }}'); $('#lang_form').submit();">
                                    {{ language.name_local }}
                                </a>
                            {% endfor %}
                            </div>
                        </li>
                        <form action="{% url 'set_language' %}" method="post" id="lang_form">{% csrf_token %}
                            <input name="language" id="lang_type" type="hidden">
                            <input name="next" type="hidden" value="{{ redirect_to }}" />
                        </form>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li {% if request.path == '/' %}class="active"{% endif %}><a href="/">{% trans "Home" %}</a></li>
                        <li {% if '/blogs' in request.path %}class="active"{% endif %}><a href="{% url 'blogs:index' %}">{% trans "Blog" %}</a></li>
                        <li {% if '/game' in request.path %}class="active"{% endif %}><a href="{% url 'games:minesweeper' %}">{% trans "Game" %}</a></li>
                        <li {% if '/upload' in request.path %}class="active"{% endif %}><a href="{% url 'upload:upload-new' %}">{% trans "Upload" %}</a></li>
                        <li {% if '/contact' in request.path %}class="active"{% endif %}><a href="{% url 'contact' %}">{% trans "Contact" %}</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container-fluid" id="main-content">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3">
                    {% block content %}
                    {% endblock %}
                    <div class="footer">
                        <a class="btn btn-info" href="https://www.mygalgame.com" target="_blank">{% trans "Theme inspired by 忧郁的弟弟" %}</a>
                        <a class="btn btn-success" href="https://github.com/KomeijiSatori/mysite" target="_blank">{% trans "Developed by Satori. All rights reserved." %}</a>
                    </div>
                </div>
            </div>

        </div>

        <div id="zan-gotop">
            <i class="fa fa-angle-up"></i>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"></script>
        <script src="{% static 'mysite/activate-power-mode.js' %}"></script>
        <script src="{% static 'mysite/cover.js' %}"></script>
        <script src="{% static 'mysite/keypress.js' %}"></script>
        <script src="{% static 'mysite/audiosynth.js' %}"></script>
    </body>
</html>

mysite/templates/mysite/contact.html
{% extends "mysite/base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Contact" %}
{% endblock %}

{% block content %}
<div class="cover-div">
    <p class="lead">
        {% blocktrans %}
        If you have any questions or problems, such as registration mail not received or password reset, please contact me at KomeijiSatori07@gmail.com. Thank you!
        {% endblocktrans %}
    </p>
</div>
{% endblock %}

mysite/templates/mysite/home.html
{% extends "mysite/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}
    {% trans "Satori's site" %}
{% endblock %}

{% block content %}

    <div class="cover-div">
        <h1 class="cover-heading">{% blocktrans with name=user.username %}Hi {{ name }}!{% endblocktrans %}</h1>
        <p class="lead">
            {% trans "Welcome to my personal website!" %}
        </p>
        <p class="lead">
            <b>{% trans "Precautions" %}</b><br/>
            {% blocktrans %}
            1. Log in is required to post a blog and upload images, if you don't have an account please click register to create one<br/>
            2. Click the avatar on the top left of the navigation bar to go to the dashboard page, where you can generate your API Key<br/>
            3. When you want to @ someone when posting a blog or comment, pay attention to add an extra space after the name you want to @<br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2018.2.14----Version Updates:</b><br/>
            1. Add Chinese language support<br/>
            2. Add language change feature<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2018.2.11----Version Updates:</b><br/>
            1. Add viewing H picture feature, press the left down right up button on the keyboard to toggle it.<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.12.7----Version Updates:</b><br/>
            1. Support Emoticons in both blog and comment posts<br/>
            2. Markdown is also supported in comments<br/>
            3. Scrollbar of browsers based on webkit looks better<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.12.1----Version Updates:</b><br/>
            1. Add @ feature in both blog and comment posts<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.11.28----Version Updates:</b><br/>
            1. Add save and load feature to minesweeper game when leaving the page<br/>
            2. Add ranking feature to minesweeper game<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.10.10----Version Updates:</b><br/>
            1. Eliminate the space of searching input to make searching result correct<br/>
            2. Advanced searching will remember the former search options<br/>
            3. Fix image upload overflow issue and add copy url button<br/>
            4. Add draft feature to blog post, and auto save when leaving the page while auto load when opening new one<br/>
            5. Comment links from the dashboard redirect to blog will jump directly to the comment<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.9.22----Version Updates:</b><br/>
            1. Fix bug of redundant blog search results in blog service<br/>
            2. Add advance blog searching feature<br/>
            3. Adjust the style of blog list page and the log in tips<br/>
            4. Adjust the position of subscribe button in blog detail page<br/>
            5. Adjust the main content full screen display on middle screens<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.9.21----Version Updates:</b><br/>
            1. Fix issue of quote block too narrow in dashboard page<br/>
            2. Add vim keyboard to view blogs and comments on dashboard page<br/>
            3. Add statistics of view count and comment count on blog detail page<br/>
            4. Adjust the style of blog list as well as dashboard page<br/>
            5. Adjust the style of blog detail page as well as blog post and update page<br/>
            6. Optimize front end code to extract common logic<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.9.19----Version Updates:</b><br/>
            1. Add instrument playing via keyboard feature<br/>
            <br/>
            {% endblocktrans %}

            {% url 'blogs:archive' 131 as kbshortcut_url %}
            {% blocktrans %}
            <b>2017.9.18----Version Updates:</b><br/>
            1. Fix picture indent issue with text<br/>
            2. Add vim keyboard to view blog list page and blog detail page<br/>
            3. Add trigger for hiding every element but the background and toggle fixed background and animated background<br/>
            4. Add <a href="{{ kbshortcut_url }}">Website keyboard shortcut reference</a><br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.9.16----Version Updates:</b><br/>
            1. Adjust blog text first line indent and line height of each row<br/>
            2. Fix comment text overflow issue<br/>
            3. Adjust the title bar to make the current title more clear<br/>
            4. Log in tips will be shown when post a comment without log in<br/>
            5. Fix comment div with redundant class<br/>
            6. Add animated background feature<br/>
            7. Add blog item flip up and down animation when scroll<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.9.9----Version Updates:</b><br/>
            1. Add minesweeper game, max size 64 x 120, minimal size 4 x 4<br/>
            2. Add send email to admin group when encounter 500 error<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.9.7----Version Updates:</b><br/>
            1. Modify file upload url<br/>
            2. Modify logic of dealing with wrong file type upload<br/>
            3. Update 400, 403, 404, 500 error pages<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.8.21----Version Updates:</b><br/>
            1. Fix comment display on narrow screens<br/>
            2. Refactor comment logic to increase security<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.8.18----Version Updates:</b><br/>
            1. Add message remind feature, you can see the amount of new messages on both navigation bar and dashboard, and the new messages will be marked<br/>
            2. Add subscribe feature, you can see the subscribed content on dashboard after subscribe<br/>
            3. The author's information will be displayed when click the author's avatar on blog detail page<br/>
            4. Fix comment display issue when encounter a new line<br/>
            <br/>
            {% endblocktrans %}

            {% url 'blogs:archive' 125 as apiref_url %}
            {% blocktrans %}
            <b>2017.8.11----Version Updates:</b><br/>
            1. Add blog api, you can play with it now<br/>
            2. Add <a href="{{ apiref_url }}">API reference book</a><br/>
            3. Fix issue of comments posted by myself will be displayed on dashboard tag 'Replies to me'<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.7.31----Version Updates:</b><br/>
            1. Add avatar upload, change and delete feature<br/>
            2. Add user's information edit page<br/>
            3. Fix issue of quoted text in reply well of dashboard can't be segmented on some browsers<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.7.30----Version Updates:</b><br/>
            1. Add dashboard page, and my blog posts, comments posts and replies to me are all available on dashboard<br/>
            2. Redirect to dashboard page after log in<br/>
            3. Adjust the update time display on blogs and comments<br/>
            4. Adjust the display of user's username and avatar<br/>
            5. Avatar is shown in blog comments, but avatar upload is still under construction<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.7.23----Version Updates:</b><br/>
            1. Comments are displayed as a tree, you can post a comment inside a comment<br/>
            2. Redesign the comment database and migrate the data and make sure not to lose the old data<br/>
            3. Blogs and comments posted by user can be modified, and last edit time is available<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.6.19----Version Updates:</b><br/>
            1. Https is used all over the website, all http requests will be redirected to https<br/>
            2. Only https links in blog content are permitted, error message will occur when http link exists<br/>
            3. Content input component on blog post page can adjust its size to the input, preview component is below the content input component<br/>
            4. Fix issue of content input component too narrow on narrow screens<br/>
            5. Fix issue of long text overflow on preview component<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.6.3----Version Updates:</b><br/>
            1. Fix issue of blog input component overlaps with preview component<br/>
            2. Add image upload feature, and you can manage the image uploaded by yourself<br/>
            3. Upload image button is added on blog post page<br/>
            4. Posting a blog without log in will redirect to log in page rather than simply return 404<br/>
            5. Fix issue of long Chinese text can't be segmented on blog detail page<br/>
            <br/>
            {% endblocktrans %}

            {% url 'blogs:archive' 105 as markdownref_url %}
            {% blocktrans %}
            <b>2017.4.29----Version Updates:</b><br/>
            1. Update background image<br/>
            2. Update blog list page UI<br/>
            3. Add return top button(on the bottom right corner)<br/>
            4. Blog supports markdown<br/>
            5. Blog post page can be visited via the button with add mark on the top left corner of search component<br/>
            6. Blog preview component is available, which can help you prevent making mistakes with markdown<br/>
            7. Add blog search feature, and you can search blogs related to any content, author or categories<br/>
            8. Add code highlight feature, please write codes with markdown<br/>
            9. Add <a href="{{ markdownref_url }}"> markdown reference</a><br/>
            10. Change the timezone, and now is UTC+8<br/>
            11. Html tags are ignored in markdown for safety<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.4.9----Version Updates:</b><br/>
            1. Successfully deployed on linode server<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.2.26----Version Updates:</b><br/>
            1. Successfully deployed on local machine<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.2.19----Version Updates:</b><br/>
            1. Add blog detail page<br/>
            2. Add pagination of blog list<br/>
            3. Add reply to blog feature<br/>
            4. Add view blogs by category feature<br/>
            5. Fix bug of posting same blog when refreshing the page<br/>
            <br/>
            {% endblocktrans %}

            {% blocktrans %}
            <b>2017.2.14----Version Updates:</b><br/>
            1. Add blog list page<br/>
            2. Add post blog feature<br/>
            3. Add log in and register page<br/>
            4. Add home page<br/>
            {% endblocktrans %}
        </p>
    </div>


{% endblock %}