blogs/api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name="blog_list"),
    url(r'^archive/(?P<pk>\d+)/$', views.BlogDetailView.as_view(), name="blog_detail"),
    url(r'^archive/(?P<pk>\d+)/edit/$', views.BlogUpdateView.as_view(), name="blog_update"),
    url(r'^post/$', views.BlogCreateView.as_view(), name="blog_post"),
    url(r'^search/$', views.BlogSearchView.as_view(), name="search"),
    url(r'^archive/(?P<pk>\d+)/comment/$', views.BlogCommentView.as_view(), name="blog_comment_list"),
    url(r'^comment/(?P<pk>\d+)/$', views.CommentListView.as_view(), name="comment_list"),
    url(r'^addComment/(?P<blog_id>[0-9]+)/$', views.CommentCreateView.as_view(), name="comment_post"),
    url(r'^addNestedComment/(?P<comment_id>[0-9]+)/$', views.NestedCommentCreateView.as_view(),
        name="nested_comment_post"),
    url(r'^comment/(?P<pk>\d+)/edit/$', views.CommentUpdateView.as_view(), name="comment_update"),
    url(r'^category/(?P<name>.+)/$', views.BlogCategoryListView.as_view(), name="category_list"),
]

blogs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^archive/(?P<blog_id>[0-9]+)/$', views.archive, name="archive"),
    url(r'^archive/(?P<blog_id>[0-9]+)/edit/$', views.blog_update, name="blog_update"),
    url(r'^post/$', views.post, name="post"),
    url(r'^search/$', views.search, name="search"),
    url(r'^comment/(?P<comment_id>[0-9]+)/$', views.getComment, name="getComment"),
    url(r'^addComment/(?P<blog_id>[0-9]+)/$', views.addComment, name="addComment"),
    url(r'^addNestedComment/(?P<comment_id>[0-9]+)/$', views.addNestedComment, name="addNestedComment"),
    url(r'^updateComment/(?P<comment_id>[0-9]+)/$', views.updateComment, name="updateComment"),
    url(r'^category/(?P<category>.+)/$', views.categoryBlogs, name="category"),

    url(r'^ajax/saveDraft/$', views.saveDraft, name="saveDraft"),
    url(r'^ajax/removeDraft/$', views.removeDraft, name="removeDraft"),
]

fileupload/urls.py
# encoding: utf-8
from django.conf.urls import url
from fileupload.views import PictureCreateView, PictureDeleteView, PictureListView

urlpatterns = [
    url(r'^$', PictureCreateView.as_view(), name='upload-new'),
    url(r'^delete/(?P<pk>\d+)/$', PictureDeleteView.as_view(), name='upload-delete'),
    url(r'^view/$', PictureListView.as_view(), name='upload-view'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.i18n import JavaScriptCatalog
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^blogs/', include('blogs.urls', namespace="blogs")),
    url(r'^contact/', views.contact, name="contact"),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^upload/', include('fileupload.urls', namespace="upload")),
    url(r'^games/', include('games.urls', namespace="games")),
    url(r'^api/blogs/', include("blogs.api.urls", namespace="blogs-api")),
]

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.conf import settings
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=500, null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    publish_time = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_update_time = models.DateTimeField(null=True, blank=True)
    text = models.TextField()
    read_count = models.IntegerField(default=0, null=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-publish_time', 'title', 'author',)


class Comment(MPTTModel):
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    publish_time = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_update_time = models.DateTimeField(null=True, blank=True)
    text = models.TextField()

    def __str__(self):
        return self.text

    """
    rebuild order by running following command in the django shell
    from blogs.models import Comment
    Comment.objects.rebuild()
    """
    class MPTTMeta:
        order_insertion_by = ['-publish_time']


class BlogCategory(models.Model):
    blog = models.ManyToManyField(Blog)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class BlogDraft(models.Model):
    title = models.CharField(max_length=500, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    category = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.author.username

    class Meta:
        ordering = ('author',)

blogs/forms.py
import re
from django import forms
from django.utils.translation import ugettext_lazy as _
from pagedown.widgets import PagedownWidget


class BlogForm(forms.Form):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': _('Title')}))
    categories = forms.CharField(required=False, label='', widget=forms.TextInput(
        attrs={'placeholder': _('Tags    Divide tags by space, could be empty')}))
    text = forms.CharField(label='', widget=PagedownWidget(show_preview=False))

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if title == "":
            raise forms.ValidationError(_("Title cannot be empty!"))
        return title

    def clean_text(self):
        text = self.cleaned_data.get('text')
        if text == "":
            raise forms.ValidationError(_("Content cannot be empty!"))
        http_links = re.findall(r'\[\d+\]: http://[^\s]*', text)
        if len(http_links) > 0:
            raise forms.ValidationError(str(_("Http link found! Only Https link is allowed! ")) + " ".join(http_links))
        return text

    def clean_categories(self):
        category_text = self.cleaned_data.get('categories')
        category = category_text.split(' ')
        if category_text == '':
            return category_text
        if '' in category:
            raise forms.ValidationError(_("Too many spaces between tags!"))
        if len(category) != len(set(category)):
            raise forms.ValidationError(_("Redundant tags exist!"))
        return category_text


class BlogCommentForm(forms.Form):
    text = forms.CharField(label="", help_text="", widget=forms.Textarea)

    def clean_text(self):
        text = self.cleaned_data.get('text')
        if text == "":
            raise forms.ValidationError(_("Content cannot be empty!"))
        return text

blogs/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView, UpdateAPIView, CreateAPIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import NotFound, ParseError

from blogs.models import Blog, Comment, BlogCategory
from blogs.service import BlogService
from .serializers import BlogListSerializer, BlogDetailSerializer, \
    BlogPostSerializer, BlogUpdateSerializer, BlogCommentListSerializer, \
    CommentPostSerializer, CommentListSerializer
from .permissions import IsOwnerOrSuperUser
from .pagination import BlogNumberPagination


class BlogListView(ListAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogListSerializer
    pagination_class = BlogNumberPagination
    http_method_names = ['get']


class BlogDetailView(RetrieveAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogDetailSerializer
    http_method_names = ['get']


class BlogUpdateView(UpdateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogUpdateSerializer
    permission_classes = [IsOwnerOrSuperUser]
    http_method_names = ['put']

    # override the default update method to avoid get_serializer with 'instance' as parameter(which will cause 500)
    def update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)

        if getattr(instance, '_prefetched_objects_cache', None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        return Response(serializer.data)

    def perform_update(self, serializer):
        title_str = serializer.validated_data.get('title')
        text_str = serializer.validated_data.get('text')
        category_str = serializer.validated_data.get('categories')
        blog_id = self.get_object().id
        blog = BlogService.update_blog_from_string(blog_id, title_str, text_str, category_str)


class BlogCreateView(CreateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogPostSerializer
    permission_classes = [IsAuthenticated]
    http_method_names = ['post']

    def perform_create(self, serializer):
        title_str = serializer.validated_data.get('title')
        text_str = serializer.validated_data.get('text')
        category_str = serializer.validated_data.get('categories')
        user = self.request.user
        # the cleaned data will swallow space which would break markdown format
        # blog.text = form.cleaned_data.get('text')
        blog = BlogService.create_blog_from_string(user, title_str, text_str, category_str)
        serializer.validated_data['id'] = blog.id


class BlogCommentView(RetrieveAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogCommentListSerializer
    http_method_names = ['get']


class CommentListView(RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentListSerializer
    http_method_names = ['get']


class CommentCreateView(CreateAPIView):
    serializer_class = CommentPostSerializer
    permission_classes = [IsAuthenticated]
    http_method_names = ['post']

    def perform_create(self, serializer):
        blog_id = self.kwargs.get('blog_id')
        try:
            blog = Blog.objects.get(id=blog_id)
        except Blog.DoesNotExist:
            blog = None
        user = self.request.user
        if blog:
            text = serializer.validated_data.get("text")
            comment = BlogService.create_comment_from_string(user, blog, text, None)
            if comment:
                serializer.validated_data['id'] = comment.id
            else:
                raise ParseError("Comment level is too high!")
        else:
            raise NotFound(detail="Blog does not exist", code=404)


class NestedCommentCreateView(CreateAPIView):
    serializer_class = CommentPostSerializer
    permission_classes = [IsAuthenticated]
    http_method_names = ['post']

    def perform_create(self, serializer):
        comment_id = self.kwargs.get('comment_id')
        try:
            parent_comment = Comment.objects.get(id=comment_id)
        except Comment.DoesNotExist:
            parent_comment = None
        user = self.request.user
        if parent_comment:
            text = serializer.validated_data.get("text")
            blog = parent_comment.blog
            comment = BlogService.create_comment_from_string(user, blog, text, parent_comment)
            if comment:
                serializer.validated_data['id'] = comment.id
            else:
                raise ParseError("Comment level is too high!")
        else:
            raise NotFound(detail="Comment does not exist", code=404)


class CommentUpdateView(UpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentPostSerializer
    permission_classes = [IsOwnerOrSuperUser]
    http_method_names = ['put']

    def perform_update(self, serializer):
        text_str = serializer.validated_data.get('text')
        comment_id = self.get_object().id
        comment = BlogService.update_comment_from_string(comment_id, text_str)

    # override self.get_serializer method to display the right serializer.data
    def update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)

        if getattr(instance, '_prefetched_objects_cache', None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        return Response(serializer.data)


class BlogCategoryListView(ListAPIView):
    serializer_class = BlogListSerializer
    pagination_class = BlogNumberPagination
    http_method_names = ['get']
    lookup_field = "name"

    def get_queryset(self):
        name = self.kwargs.get('name')
        cate = BlogCategory.objects.filter(name=name)
        if len(cate) == 1:
            return cate[0].blog.all()
        else:
            return []


class BlogSearchView(ListAPIView):
    serializer_class = BlogListSerializer
    pagination_class = BlogNumberPagination
    http_method_names = ['get']

    def get_queryset(self):
        paras = dict(self.request.GET)
        try:
            blogs = BlogService.search_blogs(**paras)
        except Exception as e:
            raise ParseError(str(e))
        return blogs

blogs/templates/blogs/base_blog_items.html
<!--List a list of blogs-->
{% load static %}
{% load i18n %}
{% load blog_tags %}
{% load avatar_tags %}

<script type="text/javascript">
    $(document).ready(function() {
        AOS.init({
            duration: 1000,
            easing: 'ease-out-back'
        });

        update_marked_indent();
    });
</script>

<script>

</script>

{% for blog in blogs %}
    <div class="blog-div well" data-aos="flip-up">
        {% block blog_extra %}{% endblock %}
        <h2>
            <span class="blog-title">
                <a href="{% url 'blogs:archive' blog.id %}">{{ blog.title }}</a>
            </span>
        </h2>
        <div class="avatar-div">
            {% avatar blog.author 64 %}
        </div>
        <p><i class="fa fa-pencil"></i> {% blocktrans with author=blog.author %}Author: {{ author }}{% endblocktrans %}</p>
        <p><i class="fa fa-clock-o"></i> {% blocktrans with date=blog.publish_time|date:"Y-m-d" time=blog.publish_time|time:"H:i:s" %}Posted: {{ date }} {{ time }}{% endblocktrans %}</p>
        {% if blog.blogcategory_set.all.count > 0 %}
        <p>
            <i class="fa fa-tags"></i> {% trans "Category:" %}
            {% for category in blog.blogcategory_set.all %}
            <span class="category-span"><a href="{% url 'blogs:category' category %}">{{ category }}</a></span>
            {% endfor %}
        </p>
        {% endif %}
        <p>
            <span><i class="fa fa-eye"></i> {% blocktrans with cnt=blog.read_count %}Views: {{ cnt }}{% endblocktrans %}</span>
            <span style="margin-left: 10px;"><i class="fa fa-comment"></i> {% blocktrans with cnt=blog.comment_set.all|length %}Comments: {{ cnt }}{% endblocktrans %}</span>
        </p>
        <!--<img class="img-responsive" src="http://placehold.it/900x300" alt="">-->
        <!--<hr>-->
        <p class="lead"><div class="blog_content marked_truncate">{{ blog.text }}</div></p>
        <a class="btn btn-primary" href="{% url 'blogs:archive' blog.id %}">{% trans "Read More" %} <i class="fa fa-chevron-right"></i></a>
    </div>
{% endfor %}

<!-- Pager -->
<ul class="pager">
    {% if blogs.has_previous %}
        <a class="btn btn-default" id="prev-btn" href="?{% url_replace page=blogs.previous_page_number %}">&lt</a>
    {% endif %}

    {% for i in page_list %}
        {% if i != '...' %}
            {% if i != blogs.number %}
                <a class="btn btn-default" href="?{% url_replace page=i %}">{{ i }}</a>
            {% else %}
                <a class="btn btn-info" href="?{% url_replace page=i %}">{{ i }}</a>
            {% endif %}
        {% else %}
            <span>...</span>
        {% endif %}
    {% endfor %}

    {% if blogs.has_next %}
        <a class="btn btn-default" id="next-btn" href="?{% url_replace page=blogs.next_page_number %}">&gt;</a>
    {% endif %}
</ul>

blogs/templates/blogs/base_search.html
{% load i18n %}
<div class="blog_post_div well">
    <form action="{% url 'blogs:search' %}" method="get">
        <div class="input-group input-group-lg">
            <input type="text" class="form-control" name="search" placeholder="{% trans 'Input whatever you want to search' %}" value={% if request.GET.search %}"{{ request.GET.search}}"{% endif %}>
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </span>
        </div>

        <div class="advance-search-div">
            <a id="advanced-search-btn">{% trans "Advanced Options" %} <i id="search-arrow" class="fa fa-angle-double-down" aria-hidden="true"></i></a>
        </div>

        <div class="advanced_search">
            <div class="row">
                <div class="col-sm-2">
                    <label class="col-form-label">{% trans "Search Fields:" %} </label>
                </div>
                <div class="col-sm-2">
                    <input class="control__input" id="field_title" type="checkbox" name="title" {% if request.GET.title %}checked{% endif %}>
                    <label class="control__label" for="field_title">{% trans "Title" %}</label>
                </div>
                <div class="col-sm-3">
                    <input class="control__input" id="field_text" type="checkbox" name="text" {% if request.GET.text %}checked{% endif %}>
                    <label class="control__label" for="field_text">{% trans "Text" %}</label>
                </div>
                <div class="col-sm-2">
                    <input class="control__input" id="field_author" type="checkbox" name="author" {% if request.GET.author %}checked{% endif %}>
                    <label class="control__label" for="field_author">{% trans "Author" %}</label>
                </div>
                <div class="col-sm-2">
                    <input class="control__input" id="field_category" type="checkbox" name="category" {% if request.GET.category %}checked{% endif %}>
                    <label class="control__label" for="field_category">{% trans "Category" %}</label>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-2">
                    <label class="col-form-label">{% trans "Publish time:" %} </label>
                </div>
                <div class="col-sm-2">
                    <input class="control__input" id="field_publish_from_check" type="checkbox" {% if request.GET.publish_from_date %}checked{% endif %}>
                    <label class="control__label" for="field_publish_from_check">{% trans "From" %} </label>
                </div>
                <div class="col-sm-3">
                    <input class="input" id="field_publish_from" name="publish_from_date" type="date" {% if request.GET.publish_from_date %}value="{{ request.GET.publish_from_date }}"{% else %}disabled{% endif %}>
                </div>

                <div class="col-sm-2">
                    <input class="control__input" id="field_publish_to_check" type="checkbox" {% if request.GET.publish_to_date %}checked{% endif %}>
                    <label class="control__label" for="field_publish_to_check">{% trans "To" %} </label>
                </div>
                <div class="col-sm-3">
                    <input class="input" id="field_publish_to" name="publish_to_date" type="date" {% if request.GET.publish_to_date %}value="{{ request.GET.publish_to_date }}"{% else %}disabled{% endif %}>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-2">
                    <label class="col-form-label">{% trans "Update time:" %} </label>
                </div>
                <div class="col-sm-2">
                    <input class="control__input" id="field_update_from_check" type="checkbox" {% if request.GET.update_from_date %}checked{% endif %}>
                    <label class="control__label" for="field_update_from_check">{% trans "From" %} </label>
                </div>
                <div class="col-sm-3">
                    <input class="input" id="field_update_from" name="update_from_date" type="date" {% if request.GET.update_from_date %}value="{{ request.GET.update_from_date }}"{% else %}disabled{% endif %}>
                </div>

                <div class="col-sm-2">
                    <input class="control__input" id="field_update_to_check" type="checkbox" {% if request.GET.update_to_date %}checked{% endif %}>
                    <label class="control__label" for="field_update_to_check">{% trans "To" %} </label>
                </div>
                <div class="col-sm-3">
                    <input class="input" id="field_update_to" name="update_to_date" type="date" {% if request.GET.update_to_date %}value="{{ request.GET.update_to_date }}"{% else %}disabled{% endif %}>
                </div>
            </div>
        </div>
    </form>
</div>

blogs/templates/blogs/index.html
{% extends "mysite/base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block title %}
    {{ title }}
{% endblock %}


{% block additional_head %}
    <!-- Custom CSS -->
    <link href="{% static 'blogs/formbase.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css" rel="stylesheet">
    <link href="{% static 'blogs/blog-home.css' %}" rel="stylesheet">
    <link href="{% static 'blogs/myblog.css' %}" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>
    <script src="{% static 'blogs/jquery.truncate.js' %}"></script>
    <script src="{% static 'blogs/render-content.js' %}"></script>
    <script src="{% static 'blogs/blog-list.js' %}"></script>
{% endblock %}


{% block content %}
    <!-- Page Content -->

    <div class="blog_post_div well">
        <div class="blog-hint-div">
            <p>{% trans "Welcome to my blog. You can post whatever you like!" %}</p>
            <p>{% blocktrans %}The blog post is using <b>markdown</b>, and here is a simple guide.{% endblocktrans %} <a href="{% url 'blogs:archive' 105 %}" target="_blank">{% trans "Markdown Guide" %}</a></p>
        {% if user.is_authenticated %}
            <div class="post-btn">
                <a class="post-btn-content" href="{% url 'blogs:post' %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
            </div>
            <a class="btn btn-primary" href="{% url 'blogs:post' %}">
                <span>{% trans "POST NOW" %} <i class="fa fa-pencil-square-o" aria-hidden="true"></i></span>
            </a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'auth_login' %}?next={{ request.get_full_path }}">
                <span>{% trans "LOGIN TO POST A BLOG" %} <i class="fa fa-sign-in" aria-hidden="true"></i></span>
            </a>
        {% endif %}
        </div>
    </div>

    {% include "blogs/base_search.html" %}

    {% include "blogs/base_blog_items.html" %}

{% endblock %}

blogs/templates/blogs/post.html
{% extends "mysite/base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load avatar_tags %}
{% load blog_tags %}


{% block title %}
    Blog Post
{% endblock %}


{% block additional_head %}
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    {{ form.media }}
    <link href="{% static 'blogs/myblog.css' %}" rel="stylesheet">
    <link href="{% static 'blogs/pagedown-widget.css' %}" rel="stylesheet">
    <link href="{% static 'blogs/emoticons.css' %}" rel="stylesheet">
    <script src="{% static 'blogs/render-content.js' %}"></script>
    <script src="{% static 'blogs/emoticons.js' %}"></script>
{% endblock %}


{% block content %}
    <br/>
    <div class="blog_post_div well">
        <div class="container-fluid">
            <h1>{% trans "Form" %}</h1>
            <form id="post_form" method="POST" novalidate action="">
                {% csrf_token %}
                {{ form|crispy }}
                {% emoticon_bar %}
                <a class="btn btn-success" href="{% url 'upload:upload-new' %}" target="_blank">{% trans "Upload Image" %}</a>
                <input type="submit" class="btn btn-primary" value="Submit" />
            </form>
        </div>

        <div class="container-fluid">
            <h1>{% trans "Preview" %}</h1>
            <div class="blog-detail_div well">
                <h1 id="preview_title"></h1>
                <p><i class="fa fa-pencil"></i> {% trans "Author:" %}
                    <a id="author">
                        <span class="avatar-span">
                        {% if blog %}
                            {% avatar blog.author 64 %}
                        {% else %}
                            {% avatar request.user 64 %}
                        {% endif %}
                        </span>
                        {% if blog %}
                            {{ blog.author }}
                        {% else %}
                            {{ request.user.username }}
                        {% endif %}
                    </a>
                </p>
                <p><i class="fa fa-clock-o"></i> <span id="preview_time">
                    {% if blog %}
                    {% blocktrans with date=blog.publish_time|date:"Y-m-d" time=blog.publish_time|time:"H:i:s" %}Posted: {{ date }} {{ time }}{% endblocktrans %}
                    {% else %}
                    {% trans "Posted: xxxx-xx-xx" %}
                    {% endif %}
                </span></p>
                {% if blog %}
                <p><small><i class="fa fa-clock-o"></i> <span id="update_time">{% trans "Last Edit: xxxx" %}</span></small></p>
                {% endif %}

                <p id="preview_category"></p>
                <p>
                    <span><i class="fa fa-eye"></i> {% trans "Views:" %} {% if blog %}{{ blog.read_count }}{% else %}0{% endif %}</span>
                    <span style="margin-left: 10px;"><i class="fa fa-comment"></i> {% trans "Comments:" %} {% if blog %}{{ blog.comment_set.all | length }}{% else %}0{% endif %}</span>
                </p>
                <div class="blog_content marked_content" id="preview_content"></div>
            </div>

        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function(){
            $('textarea').each(function ()
            {
                this.setAttribute('style', 'height:' + (this.scrollHeight) + 'px;overflow-y:hidden;resize: none;');
            }).on('input', function () {
                this.style.height = 'auto';
                this.style.height = (this.scrollHeight) + 'px';
            });

            function set_title()
            {
                $("#preview_title").text($("#id_title").val());
            }
            function set_content() {
                $("#preview_content").html(render_content($("#id_text").val()));
                update_marked_indent();
            }
            function set_category() {
                var text = $("#id_categories").val();
                if (text === '')
                {
                    $("#preview_category").html('');
                    return;
                }
                var cates = text.split(" ");
                var res = '<p><i class="fa fa-tags"></i> {% trans "Category:" %} ';
                for (var i = 0; i < cates.length; i++) {
                    res += '<span class="category-span"><a>' + cates[i] + '</a></span> '
                }
                res += '</p>';
                $("#preview_category").html(res);
            }
            function set_time() {
                var d = new Date();
                var curr_date = d.getDate();
                var curr_month = d.getMonth();
                curr_month++;
                var curr_year = d.getFullYear();
                var curr_hour = d.getHours();
                var curr_minute = d.getMinutes();
                var curr_second = d.getSeconds();
                {% if blog %}
                $("#update_time").html("{% trans 'Last Edit:' %} "+ curr_year + "-" + curr_month + "-" + curr_date
                + " " + curr_hour + ":" + curr_minute + ":" + curr_second);
                {% else %}
                $("#preview_time").html("{% trans 'Posted:' %} " + curr_year + "-" + curr_month + "-" + curr_date
                + " " + curr_hour + ":" + curr_minute + ":" + curr_second);
                {% endif %}
            }

            // initial set
            set_title();
            set_content();
            set_category();
            set_time();
            // listen events
            $("#id_title").bind('input propertychange', set_title);

            $("#id_text").bind('input propertychange', set_content);

            $("#id_categories").bind('input propertychange', set_category);

            setInterval(set_time, 1000);

            // listen list and button click event to renew content generated by button
            $(document).on('click', '.wmd-button', function(){
                set_content();
            });
            // fix img url and url window
            $(document).on('click', "input[type='button'][value='OK']", function(){
                set_content();
            });
            // fix emoticon
            $(document).on('click', '.emoticon-set img', function(){
                set_content();
            });

            {% if save_draft %}
            // save the changes before leaving the page
            $(window).bind('beforeunload', function(e) {
                var title = $("#id_title")[0].value;
                var text = $("#id_text")[0].value;
                var category = $("#id_categories")[0].value;
                $.ajax({
                    type: "POST",
                    async: false,
                    url: "{% url 'blogs:saveDraft' %}",
                    data: {
                        "title": title,
                        "text": text,
                        "category": category,
                        "csrfmiddlewaretoken": '{{ csrf_token }}'
                    }
                });
                return undefined;
            });
            // remove draft when hitting submit
            $('#post_form').submit(function() {
                $(window).unbind('beforeunload');
                $.ajax({
                    type: "GET",
                    async: false,
                    url: "{% url 'blogs:removeDraft' %}"
                });
                return true;
            });
            {% endif %}
        })
    </script>
{% endblock %}